### PR TITLE
FreeDesktop compliant ascii-design.desktop

### PR DESCRIPTION
**Pull request by Mailaender**
@openSUSE is a little strict about this and otherwise aborts builds. I just created an RPM https://build.opensuse.org/request/show/214391 which you can link it via http://software.opensuse.org/package/ascii-design at your homepage.

### CODE REVIEW

**Comment by cicku** [comment]
Not only SUSE.

+1

**Comment by Faster3ck** [comment]
Hi, I've just fixed the issue. Check the new commit

**Comment by Mailaender** [comment]
https://github.com/Faster3ck/Ascii-Design/commit/583e8833bb74a36fc5a7f3affe419a1056e06e49#diff-2

**Comment by Mailaender** [comment]
Still missing the http://standards.freedesktop.org/desktop-entry-spec version, removed the encoding, not a valid category and missing a generic name which causes glitches on KDE.

**Comment by Faster3ck** [comment]
Hi, I've committed the fixed desktop file trying to follow the specifications in the document you linked and checking other desktop files of some kde applications installed on my system.
I hope it's ok now. Otherwise could you specify me what entries I've missed?

**Comment by Mailaender** [comment]
Looking good. This will add some nice polishing to your application and not cause package maintainers pain anymore. =) Well done. Thanks.

**Comment by Faster3ck** [comment]
Thanks to you for the tips :)

**Pull request closed without merging**
